language: ruby
rvm:
  - 1.9.3
bundler_args: --without development
before_script:
  - psql -c 'create database winloss_test' -U postgres
  - cp config/database.example.yml config/database.yml
  - RAILS_ENV=test bundle exec rake --trace db:migrate
script:
  - rspec spec
